package com.enums;

public enum HvacSystems
{
	AIR_CONDITIONER,
	AIR_HANDLER,
	COOLING,
	DUCTLESS_AIR_CONDITIONER,
	DUSTLESS_HEAT_PUMP,
	FURNACE,
	HEAT_PUMP,
	HEATING,
	HUMIDIFIER,
	ROOFTOP,
	SPLIT_AIR_CONDITIONER,
	SPLIT_HEAT_PUMP,
	STANDING_BOILER,
	TANKED_WATER_HEATER,
	TANKLESS_WATER_HEATER,
	WALLHUNG_BOILER,
	WATER_HEATER,
	NOT_APPLICABLE
}
