package com.enums;

public enum HvacFuels
{
	GAS,
	ELECTRIC,
	GEOTHERMAL,
	REFRIGERANT_R22,
	REFRIGERANT_R410A,
	GAS_ELECTRIC,
	GAS_GEOTHERMAL,
	GEOTHERMAL_REFRIGERANT_R22,
	GEOTHERMAL_REFRIGERANT_R410A,
	OIL,	
	NOT_APPLICABLE
}
